# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (daily)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nick2bad4u
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          commits_authoring: nick2bad4u
          config_display: large
          config_octicon: yes
          config_timezone: America/Detroit
          config_twemoji: yes
          # plugin_achievements: yes
          # plugin_achievements_display: detailed
          # plugin_achievements_secrets: yes
          # plugin_achievements_threshold: X
          # Achievements plugin disabled due to Projects (classic) API deprecation. Re-enable when plugin is updated.
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 20
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_fortune: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 12
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 20
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
          # plugin_projects: yes
          # plugin_projects_descriptions: yes
          # plugin_projects_limit: 4
          # Projects (classic) plugin disabled due to deprecation. See: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/
          # plugin_pagespeed: yes
          # plugin_pagespeed_detailed: yes
          # plugin_pagespeed_pwa: yes
          # plugin_pagespeed_screenshot: yes
          # plugin_pagespeed_url: https://fitfileviewer.typpi.online
          # plugin_pagespeed_token: ${{ secrets.METRICS_PAGESPEED_TOKEN }}
          # Pagespeed plugin disabled due to repeated API errors. Re-enable after debugging the URL and API response.
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          # plugin_sponsors: yes
          # plugin_sponsors_past: yes
          # plugin_sponsors_sections: goal, list, about
          # plugin_sponsors_size: 24
          # plugin_sponsors_title: Sponsor Me!
          # Sponsors plugin disabled due to error. Re-enable if fixed upstream.
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 365
          # plugin_stargazers_worldmap: yes
          # Stargazers worldmap disabled (requires Google Maps API token). To re-enable, add:
          # plugin_stargazers_maps_token: ${{ secrets.METRICS_MAPS_TOKEN }}
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
          plugin_stars: yes
          plugin_stars_limit: 8
          # plugin_steam: yes
          # plugin_steam_achievements_limit: 8
          # plugin_steam_games_limit: 8
          # plugin_steam_playtime_threshold: 4
          # plugin_steam_recent_games_limit: 3
          # plugin_steam_sections: player, most-played, recently-played
          # plugin_steam_user: Nick2bad4u
          # plugin_steam_token: ${{ secrets.METRICS_STEAM_TOKEN }}
          # Steam plugin disabled due to API error 400. Double-check your Steam user, API key, and profile privacy. Re-enable after fixing.
          # plugin_support: yes
          # Support plugin disabled (account does not exist on github.community)
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: yes
          repositories_forks: yes
